export interface PowerModel {
ActiveEnergyOutlet: number,
ActiveEnergyInput: number,
ReactiveEnergyOutlet: string,
ReactiveEnergyInput:string,
ActivePowerOutlet:string,
ActivePowerInput:string,
ReactivePowerOutlet:string,
ReactivePowerInput:string,
ActivePowerOutlet1:string,
ActivePowerInput1:string,
ActivePowerOutlet2:string,
ActivePowerInput2:string,
ActivePowerOutlet3:string,
ActivePowerInput3:string,
ReactivePowerOutlet1:string,
ReactivePowerInput1:string,
ReactivePowerOutlet2:string,
ReactivePowerInput2:string,
ReactivePowerOutlet3:string,
ReactivePowerInput3:string,
PhaseCurrent1:string,
PhaseCurrent2:string,
PhaseCurrent3:string,
PhaseVoltage1:string,
PhaseVoltage2:string,
PhaseVoltage3:string,
}